### ISSUE TITLE
Add example proposals/templates

### ISSUE THREAD

**Issue by xmunoz** [psf/project-funding-wg#10]
At the last meeting we discussed adding recent proposals (or sections thereof) to this repo. Let's actually do that!

**Comment by ericholscher** [comment]
I have a public version of a CZI grant that was published by the Jupyterbook team. I can add it with their permission. Should we just have a directory with proposals in it?

**Comment by xmunoz** [comment]
Sure! @brainwane how do you feel about adding some of the proposals that you worked on?

**Comment by brainwane** [comment]
@xmunoz Sorry for the wait - I think that's a great idea! I don't have time to do it till much later this month but would be fine with someone else doing it. I suggest someone take a look at the ones I've shared within the group and checking them for any private info that should NOT be shared. As long as there isn't any redaction necessary, yes, go ahead and put PDFs in a directory in this repository.

**Comment by xmunoz** [comment]
Cool, I'll go ahead and assign this issue to myself, and hope to get to it in the next week or two.
