### ISSUE TITLE
List previously completed and in-progress grants

### ISSUE THREAD

**Issue by di** [psf/project-funding-wg#14]
I'd like to have a place where I can point potential funders to our successful track record requesting funding and using it to complete projects. Ideally this would include:

* the project in question
* the funder
* the amount funded
* the composition of the team that was contracted to work on the project
* the initial grant request
* any reports that were generated during the project or after it was completed
* any other "results"

**Comment by brainwane** [comment]
@di If you want to pair on this for an hour next week, I'm available.

**Comment by di** [comment]
@brainwane Sounds great! Can you schedule time that works for you via https://calendly.com/di_codes/60?

**Comment by brainwane** [comment]
@di is working on this now -- thanks and glad my [notes](https://wiki.python.org/psf/PackagingWG) are helpful!
