### ISSUE TITLE
Add advice and fundable ideas to resources

### ISSUE THREAD

**Issue by brainwane** [psf/project-funding-wg#2]
It's pretty skeletal, but let's add 2 pages to this repo:

Ideas for fundable projects

Currently listing:

  * https://github.com/python/steering-council/issues
  * https://github.com/psf/fundable-packaging-improvements 

Advice for volunteers

Starting with some placeholders for advice about:

 * Developing budgets, using resources like [the OSAOS Handbook budgeting guide](https://osaos.codeforscience.org/budgeting/)
 * Grantcraft (submitting proposals, drafting interim reports, and keeping up relationships with funders afterward -- like in [this Conservancy blog post](https://sfconservancy.org/blog/2020/apr/02/remotefundraising/))
 * Coordinating with the PSF, other WGs, and the Steering Council to decide priorities

**Comment by brainwane** [comment]
@marlenezw and @xmunoz - if you have time, resolving this would be a great thing!

**Comment by marlenezw** [comment]
I'll try and get to this over the weekend :)

**Comment by xmunoz** [comment]
I'll take a look today!

**Comment by brainwane** [comment]
Great, thank you both!
